apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "order.name" . }}
  labels:
    {{- include "order.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.googleServiceAccount | quote }}
automountServiceAccountToken: false
